### ISSUE TITLE
Feature Request: Whitelist logs on vm_4?

### ISSUE THREAD

**Issue by KeksXtreme** [Elemend/Vein-Miner-Version-2#1]
I'd love to be able to cut down trees (preferably of any type/variation) with the basic veinminer (vm_4) too. Would you be willing to add logs to the list of whitelisted blocks?
Also have you thought about adding something similar to QuickLeafDecay (if that's even possible using datapacks only)?

Thanks for your work. Appreciate it!

**Comment by Elemend** [comment]
The lightweight Version (vm_4) is specifically designed to only work with ores and the Block Detection System has no "whitelist" so to speak, it isn't configurable. To make it configurable, and let you choose the Blocks it would work with, wouldn't make it work either. Because that would still require the Player to have the knowledge about how the files in the Datapack work together and how the commands work. At this point they might as well make the changes themselves. 

Fast Leave Decay is beyond of what Datapacks can change. Only direct changes to the Gamecode would be able to change that.
