### ISSUE TITLE
No hunger or usur for me

### ISSUE THREAD

**Issue by lipki** [Elemend/Vein-Miner-Version-2#6]
Hello, on a server, I am the first op (but not the only one)
When I use vein miner, it's another player who takes the hunger.
And my tools do not wear out.
So I'm happy: D, but it's still a bug.

The others op not this problem.

**Comment by Elemend** [comment]
Can you look what id scores you and the other players have?
"/scoreboard objectives setdisplay sidebar vm_id" in chat should show that everybody has a different score. If there are same values on different players, reset the score.

**Comment by lipki** [comment]
They are all different, for info we are 12, so from 1 to 12

**Comment by lipki** [comment]
vm_diapick stays at zero for me, but increases for others.

**Comment by Elemend** [comment]
That is most likely the problem. I don't know how it was even possible that you got the score of 0. Did you reset your score anyway? Does it get set to 0 again?

**Comment by lipki** [comment]
vm_id = 1
for me

vm_diapick (and the others) = 0.
for me and several other players.

I do not know how to reset.

**Comment by lipki** [comment]
I managed to solve the problem by giving me another id available.

But the problem does not seem to come from the id 1

**Comment by Elemend** [comment]
As you can Imagine, A telediagnosis makes this not easier to solve. I did some digging around and found that maybe the problem occurs when the scores for checking the players hungerlevel and their id score overlap. To change that, I can give you a file "playerinput" that you need to insert into the functions folder in the vein miner directory so that it reads as this: .."vm\functions\playerinput.mcfunction". [Link](https://drive.google.com/open?id=1rr85lOiC2pAGmEEOnOnYbkUJhmDmqaVI)

An additional Problem is that I could never test this datapack in Multiplayer and as such can't recreate any Issues that would occur then. This attempt at a solution is a shot in the blue and the Issue might be related to something entirely different, but we'll see.

**Comment by Elemend** [comment]
I changed some things, and Hope this prevents any errors. [Link](https://drive.google.com/open?id=1bdnu4VwiaSwOPlvblBhvEXasQgmcrNNQ) Let me know if this new Version changes anything.

**Comment by Elemend** [comment]
I got inspired to look over the datapack again and I compacted some of the commands. I would like to update the download of the repository. In order for me make this update official, I need to know if the changes in the datapack I gave you the Link to in my previous answer does fix the Issue you encountered.

**Comment by Elemend** [comment]
Fixed in an Upcoming Update.
